### ISSUE TITLE
Missing configuration files.

### ISSUE THREAD

**Issue by kyrahabattoir** [mattmatterson111/NSV-Luna-Redux-Restoration#2]
Might be useful to include samples for the following:

## ERROR: File not found (config/names/lifedream.txt)

The admins.txt format appears to be:
ckey - rank

**Comment by mattmatterson111** [comment]
Admins I think is the most important. I have not seen the other three anywhere. I'm not sure where they could be found.

**Comment by mattmatterson111** [comment]
Mostly fixed in 82b0f8a318a2653dbdb51006d35bdef691f654d7. The other txts aren't used anywhere from what I can tell.
